In [4]:
import numpy as np
import pandas as pd

In [5]:
# URL of the CSV file in GitHub
base_url = "https://raw.githubusercontent.com/cs-arnab/Recommendation-System/master/Data%20Set/"
movies = base_url + "tmdb_5000_movies.csv"
credits = base_url + "tmdb_5000_credits.csv"

In [6]:
movies = pd.read_csv(movies)
credits = pd.read_csv(credits)

In [7]:
print(movies.shape)
movies.head(2)

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [8]:
print(credits.shape)
credits.head(2)
# credits.head(2)['title'].values

(4803, 4)


movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [9]:
movies = movies.merge(credits,on='title')
print(movies.shape)
movies.head(2)

(4809, 23)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995   
1  Pirates of the Caribbean: At World's End          6.9       4500      285   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  

[2 rows x 23 columns]

In [10]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4809 non-null   int64  
 1   genres                4809 non-null   object 
 2   homepage              1713 non-null   object 
 3   id                    4809 non-null   int64  
 4   keywords              4809 non-null   object 
 5   original_language     4809 non-null   object 
 6   original_title        4809 non-null   object 
 7   overview              4806 non-null   object 
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object 
 10  production_countries  4809 non-null   object 
 11  release_date          4808 non-null   object 
 12  revenue               4809 non-null   int64  
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object 
 15  status               

In [11]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [12]:
# we need 3 column to process
# movie_id, title and tags
# tags = overview	+ genres + keywords + cast + crew

# 1. drop missing data
print(movies.isnull().sum())
movies.dropna(inplace=True)
# 2. check duplicate
print(movies.duplicated().sum())
movies.drop_duplicates(inplace=True)


movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64
0


In [13]:
import ast
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

# The ast.literal_eval(text) function in Python is used to safely evaluate
# an expression or a string containing a Python literal (such as a dictionary,
# list, tuple, number, string, boolean, or None). It's safer than using eval()
# because it only evaluates literals and does not execute arbitrary code.
text = '[1, 2, 3, 4, 5]'
print(text)
print(type(text))

result = ast.literal_eval(text)
print(result)  # Output: [1, 2, 3, 4, 5]
print(type(result))  # Output: <class 'list'>
# [1, 2, 3, 4, 5] <class 'str'> -> [1, 2, 3, 4, 5] <class 'list'>

[1, 2, 3, 4, 5]
<class 'str'>
[1, 2, 3, 4, 5]
<class 'list'>


In [14]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [15]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [16]:
movies['cast'] = movies['cast'].apply(convert)

In [17]:
#find out director
import json
# Sample JSON data
json_data = movies['crew'][0]

# Load JSON data
data = json.loads(json_data)

# Convert to DataFrame
df = pd.json_normalize(data)
df.head(2)

credit_id department  gender    id                job  \
0  52fe48009251416c750aca23    Editing       0  1721             Editor   
1  539c47ecc3a36810e3001f87        Art       2   496  Production Design   

                name  
0  Stephen E. Rivkin  
1        Rick Carter

In [18]:
# print(df)
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [19]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [20]:
movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   

                                                cast              crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...   [James Cameron]  
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...  [Gore Verbinski]

In [21]:
# In the 22nd century -> In, the, 22nd, century,
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(2)

movie_id                          title  \
4032    116584  Valley of the Heart's Delight   
350       4327               Charlie's Angels   

                                               overview  \
4032  [When, a, fatal, kidnapping, ignites, a, fires...   
350   [Aspects, of, this, take, on, the, 1970s, hit,...   

                                            genres  \
4032                                       [Drama]   
350   [Action, Adventure, Comedy, Crime, Thriller]   

                                               keywords  \
4032                                                 []   
350   [martial arts, female friendship, millionaire,...   

                                                   cast          crew  
4032  [Pete Postlethwaite, Gabriel Mann, Emily Harri...  [Tim Boxell]  
350   [Cameron Diaz, Lucy Liu, Drew Barrymore, Bill ...         [McG]

In [22]:
movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   

                                                cast              crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...   [James Cameron]  
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...  [Gore Verbinski]

In [23]:
# Sam Worthington -> SamWorthington
# Removing spaces ensures consistency, improves search accuracy, reduces
# noise, normalizes data, and enhances efficiency in recommender systems
# and data processing.

def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [24]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)
movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   

                                                cast             crew  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...   [JamesCameron]  
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...  [GoreVerbinski]

In [25]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [26]:
movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   

                                                cast             crew  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...   [JamesCameron]   
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...  [GoreVerbinski]   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...

In [27]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new['tags'] = new['tags'].apply(lambda x: " ".join(x))

for i,v in enumerate(new['tags']):
  new['tags'][i] = v.lower()

print(len(new['tags']))
new.head(2)

Streaming output truncated to the last 5000 lines.
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new['tags'][i] = v.lower()
<ipython-input-27-a4f40dd14f09>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'][i] = v.lower()
<ipython-input-27-a4f40dd14f09>:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values

4806


movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...

In [28]:
new['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanm

In [29]:
# import nltk
# from nltk.stem.porter import PorterStemmer
# ps=PorterStemmer()
# def stem(text):
#   y=[]
#   for i in text.split():
#     y.append(ps.stem(1))
#   return " ".join(y)
# error occur

In [30]:
# ps = PorterStemmer(): This creates an instance of the PorterStemmer class,
# which is a widely used stemming algorithm in NLP. Stemming algorithms like
# Porter's reduce words to their base or root form by removing suffixes.
# Love, Loving, Loved -> love

import nltk
from nltk.stem.porter import PorterStemmer

nltk.download('punkt')  # Download the punkt tokenizer if you haven't already
ps = PorterStemmer()
def stem(text):
    tokens = nltk.word_tokenize(text)  # Tokenize the text into words
    stemmed_tokens = [ps.stem(token) for token in tokens]  # Apply stemming to each word
    return " ".join(stemmed_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [31]:
new['tags'] = new['tags'].apply(stem)

In [32]:
# Text to vector techniques are methods used to convert textual data into
# numerical vectors, which can be processed by machine learning algorithms.

# Here are some common text to vector techniques:

# 1. Bag of Words (BoW):
#    - Description: Represents text as a set of unique words, ignoring grammar
#    and word order.
#    - Advantages: Simple, captures word frequencies.
#    - Disadvantages: Loses word order and context.
#    - Example Techniques: CountVectorizer in scikit-learn, BoW in Natural
#    Language Toolkit (NLTK).

# 2. Term Frequency-Inverse Document Frequency (TF-IDF):
#    - Description: Weighs words based on their frequency in a document
#    relative to their frequency in the entire corpus.
#    - Advantages: Considers word importance and document specificity.
#    - Disadvantages: Ignores word order and context.
#    - Example Techniques: TfidfVectorizer in scikit-learn.

# 3. Word Embeddings (Word2Vec, GloVe, FastText):
#    - Description: Represents words as dense vectors in a continuous
#    vector space, capturing semantic relationships.
#    - Advantages: Captures word semantics and relationships.
#    - Disadvantages: Requires large amounts of data for training.
#    - Example Techniques: Word2Vec, GloVe, FastText.

# 4. Doc2Vec (Paragraph Vector):
#    - Description: Extends Word2Vec to represent entire documents as vectors.
#    - Advantages: Captures document semantics.
#    - Disadvantages: Requires large amounts of data for training.
#    - Example Techniques: Doc2Vec in gensim.

# 5. Topic Modeling (Latent Dirichlet Allocation, LDA):
#    - Description: Identifies latent topics in a collection of documents
#    and represents documents based on topic distributions.
#    - Advantages: Captures document themes and topics.
#    - Disadvantages: Requires domain knowledge for interpretation.
#    - Example Techniques: Latent Dirichlet Allocation (LDA) in gensim,
#    scikit-learn.

# 6. Transformer-based Models (BERT, GPT-3):
#    - Description: Utilizes transformer architecture to generate contextualized
#    word embeddings or document representations.
#    - Advantages: Captures context and semantics effectively.
#    - Disadvantages: Computationally intensive, requires large pre-trained
#    models.
#    - Example Techniques: BERT, GPT-3.

# Each technique has its strengths and weaknesses, and the choice depends on
# the specific task, data characteristics, and computational resources available.

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [35]:
vector = cv.fit_transform(new['tags']).toarray()
# print(vector.shape)
print(vector)
# cv.get_feature_names_out()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [37]:
import math

def calculate_cos_theta(angle_in_degrees):
    angle_in_radians = math.radians(angle_in_degrees)
    cos_theta = math.cos(angle_in_radians)
    return cos_theta

# Example usage
def fun(angle_degrees):
  for i in range(0,angle_degrees):
    cos_value = calculate_cos_theta(i)
    print(f"The cosine of {i} degrees is {cos_value}")

angle_degrees = 91
fun(angle_degrees)

The cosine of 0 degrees is 1.0
The cosine of 1 degrees is 0.9998476951563913
The cosine of 2 degrees is 0.9993908270190958
The cosine of 3 degrees is 0.9986295347545738
The cosine of 4 degrees is 0.9975640502598242
The cosine of 5 degrees is 0.9961946980917455
The cosine of 6 degrees is 0.9945218953682733
The cosine of 7 degrees is 0.992546151641322
The cosine of 8 degrees is 0.9902680687415704
The cosine of 9 degrees is 0.9876883405951378
The cosine of 10 degrees is 0.984807753012208
The cosine of 11 degrees is 0.981627183447664
The cosine of 12 degrees is 0.9781476007338057
The cosine of 13 degrees is 0.9743700647852352
The cosine of 14 degrees is 0.9702957262759965
The cosine of 15 degrees is 0.9659258262890683
The cosine of 16 degrees is 0.9612616959383189
The cosine of 17 degrees is 0.9563047559630354
The cosine of 18 degrees is 0.9510565162951535
The cosine of 19 degrees is 0.9455185755993168
The cosine of 20 degrees is 0.9396926207859084
The cosine of 21 degrees is 0.93358042649

In [38]:
print(similarity.shape)
print(similarity[0])
print(similarity[1])
print(similarity[2])
print(similarity[3])

(4806, 4806)
[1.         0.06451986 0.07372098 ... 0.05808023 0.02173913 0.        ]
[0.06451986 1.         0.0729325  ... 0.01915301 0.         0.0210538 ]
[0.07372098 0.0729325  1.         ... 0.04376881 0.         0.        ]
[0.07485231 0.04443104 0.05076731 ... 0.05332859 0.04491139 0.0732763 ]


In [39]:
print(new['title'] == 'The Lego Movie')
print("Movie Index : ",new[new['title'] == 'The Lego Movie'].index[0])

0       False
1       False
2       False
3       False
4       False
        ...  
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4806, dtype: bool
Movie Index :  744


In [40]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [41]:
recommend('Gandhi')

Namastey London
Taxi to the Dark Side
Downfall
A Passage to India
Ramanujan


In [42]:
# my function
# reco=sorted(list(enumerate(similarity[744])),reverse=True,key = lambda x: x[1])[1:6]
# for i,v in enumerate(reco):
#   print("similarity score : ","{:.3f}".format(v[1]),", Movie Id :", v[0],", Name :",new.iloc[v[0]].title)

def recommend1(movie):
  index = new[new['title'] == movie].index[0]
  reco=sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])[1:6]
  for i,v in enumerate(reco):
    print("similarity score : ","{:.3f}".format(v[1]*100),", Movie Id :", v[0],", Name :",new.iloc[v[0]].title)


In [43]:
# If the movie name is there, it shows results; otherwise, it gives us an error.
recommend1('The Iceman')

similarity score :  40.712 , Movie Id : 4498 , Name : Top Hat
similarity score :  38.790 , Movie Id : 3301 , Name : Swelter
similarity score :  37.998 , Movie Id : 2873 , Name : From Justin to Kelly
similarity score :  36.927 , Movie Id : 4458 , Name : Ruby in Paradise
similarity score :  36.784 , Movie Id : 4113 , Name : Meek's Cutoff
