In [4]:
import numpy
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    '''
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: |D| * K (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with a and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:
            break
    return P, Q.T

In [5]:
import numpy as np

def matrix_factorization_not_used(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if e < 0.001:
            break
    return P, Q.T

# Example usage
R = [
     [3, 1, 1, 3, 1],
     [1, 2, 4, 1, 3],
     [3, 1, 1, 3, 1],
     [4, 3, 5, 4, 4],
    ]

R = np.array(R)

# Set the number of latent features
K = 2

# Initialize random matrices P and Q
P = np.random.rand(len(R), K)
Q = np.random.rand(len(R[0]), K)

# Run matrix factorization
result_P, result_Q = matrix_factorization(R, P, Q, K)

print("Matrix P:")
print(result_P)
print("\nMatrix Q:")
print(result_Q)

result = np.round(np.dot(P, Q.T), 3)  # Transpose Q for correct matrix multiplication
print("\nMatrix Multiplication Result:")
print(result)
print("\nOriginal Matrix R:")
print(R)


Matrix P:
[[0.06375223 1.56237468]
 [1.90809797 0.18961592]
 [0.06409929 1.56205939]
 [1.97232649 1.7515599 ]]

Matrix Q:
[[0.33906486 1.89414326]
 [0.98253161 0.59949382]
 [2.02738789 0.55986788]
 [0.33975575 1.89349325]
 [1.50458247 0.58003727]]

Matrix Multiplication Result:
[[2.981 0.999 1.004 2.98  1.002]
 [1.006 1.988 3.975 1.007 2.981]
 [2.98  0.999 1.005 2.98  1.002]
 [3.986 2.988 4.979 3.987 3.983]]

Original Matrix R:
[[3 1 1 3 1]
 [1 2 4 1 3]
 [3 1 1 3 1]
 [4 3 5 4 4]]


In [6]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
     [2,1,3,0],
    ]
R = numpy.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 3
P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)
nP, nQ = matrix_factorization(R, P, Q, K)
nR = numpy.dot(nP, nQ.T)
print(nR)

[[4.99703685 2.91208581 5.34095144 1.00148266]
 [3.96356931 1.75271858 4.21963364 1.00108815]
 [1.03364132 0.89477818 4.04244044 4.96903224]
 [0.98410449 0.27338192 3.25122593 3.98090356]
 [2.82055894 1.13256144 4.95072695 3.99989146]
 [1.98466474 1.05698409 2.98024255 1.868081  ]]
